---
jobs:  
- name: deploy to env
  serial: true
  plan:
  - get: git-example
    trigger: true

  - task: deploy-to-test-env
    config:
      platform: linux
      image: docker:///busybox
      inputs: 
        - name: git-example
      run: 
        path: sh
        args: ["git-example/pretend-scripts/standup.sh"]

  - put: test-environments
    params:
      add: deploy-to-test-env/pool_params
  - put: test-environments
    params:
      claim: disposable-test-env 

- name: test against env
  plan:
  - get: test-environments
    trigger: true
    passed: [deploy to env]
  - get: git-example
    passed: [deploy to env]
  - task: test-against-env
    config:
      platform: linux
      image: docker:///busybox
      inputs:
        - name: test-environments
        - name: git-example
      run: 
        path: sh
        args: ["git-example/pretend-scripts/test.sh"]
    ensure:
      do:
        - task: teardown-environment
          config:
            platform: linux
            image: docker:///busybox
            inputs:
              - name: test-environments
              - name: git-example
            run: 
              path: sh
              args: ["git-example/pretend-scripts/teardown.sh"]
        - put: test-environments
          params: {remove: test-environments}

resources:  
- name: git-example
  type: git
  source:
    uri: git@github.com:moredip/concourse-disposable-test-env-example.git
    branch: master
    private_key: {{github_deploy_key}}

- name: test-environments
  type: pool
  source:
    uri: git@github.com:moredip/concourse-disposable-test-env-example.git
    branch: locks
    pool: pools/disposable-environments
    private_key: {{github_deploy_key}}
